interface test.AnyType

type Config (
    name: string,
    metadata: any,
    extra: ?any
)

method SetConfig(config: Config, data: any) -> (id: string)
method GetConfig(id: string) -> (config: Config)
method ProcessData(data: any) -> (result: any)
